version: '3'
services:
  web:
    ports:
      - "3030:3030"
    build: .
    command: smashing start -a 0.0.0.0
    env_file:
      - .env.docker
    tty: true
    stdin_open: true
    volumes:
      - .:/dashboard-sdm
